/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TaskSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  tasksFolder: "Tasks",
  projectsFolder: "Projects",
  areasFolder: "Areas",
  enableAutoSync: true,
  syncInterval: 3e5,
  // 5 minutes
  templateFolder: "Templates",
  useTemplater: false,
  defaultTaskTemplate: "",
  defaultProjectTemplate: "",
  defaultAreaTemplate: ""
};
var TaskSyncPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Loading Task Sync Plugin");
    await this.loadSettings();
    this.addSettingTab(new TaskSyncSettingTab(this.app, this));
    this.addCommand({
      id: "open-task-dashboard",
      name: "Open Task Dashboard",
      callback: () => {
        console.log("Opening task dashboard...");
      }
    });
    this.addCommand({
      id: "add-task",
      name: "Add Task",
      callback: () => {
        console.log("Adding new task...");
      }
    });
    this.addCommand({
      id: "add-project",
      name: "Add Project",
      callback: () => {
        console.log("Adding new project...");
      }
    });
    this.addCommand({
      id: "add-area",
      name: "Add Area",
      callback: () => {
        console.log("Adding new area...");
      }
    });
  }
  onunload() {
    console.log("Unloading Task Sync Plugin");
  }
  async loadSettings() {
    try {
      const loadedData = await this.loadData();
      this.settings = Object.assign({}, DEFAULT_SETTINGS, loadedData);
      await this.migrateSettings();
      this.validateSettings();
    } catch (error) {
      console.error("Task Sync: Failed to load settings:", error);
      this.settings = { ...DEFAULT_SETTINGS };
    }
  }
  async saveSettings() {
    try {
      await this.saveData(this.settings);
    } catch (error) {
      console.error("Task Sync: Failed to save settings:", error);
      throw error;
    }
  }
  async migrateSettings() {
    if (!this.settings.hasOwnProperty("enableAutoSync")) {
      this.settings.enableAutoSync = DEFAULT_SETTINGS.enableAutoSync;
    }
  }
  validateSettings() {
    if (typeof this.settings.syncInterval !== "number" || this.settings.syncInterval < 6e4) {
      console.warn("Task Sync: Invalid sync interval, using default");
      this.settings.syncInterval = DEFAULT_SETTINGS.syncInterval;
    }
    const folderFields = ["tasksFolder", "projectsFolder", "areasFolder", "templateFolder"];
    folderFields.forEach((field) => {
      if (typeof this.settings[field] !== "string") {
        console.warn(`Task Sync: Invalid ${field}, using default`);
        this.settings[field] = DEFAULT_SETTINGS[field];
      }
    });
  }
};
var TaskSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Task Sync Settings" });
    containerEl.createEl("h3", { text: "Folder Configuration" });
    new import_obsidian.Setting(containerEl).setName("Tasks Folder").setDesc("Folder where task files will be stored").addText((text) => text.setPlaceholder("Tasks").setValue(this.plugin.settings.tasksFolder).onChange(async (value) => {
      this.plugin.settings.tasksFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Projects Folder").setDesc("Folder where project files will be stored").addText((text) => text.setPlaceholder("Projects").setValue(this.plugin.settings.projectsFolder).onChange(async (value) => {
      this.plugin.settings.projectsFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Areas Folder").setDesc("Folder where area files will be stored").addText((text) => text.setPlaceholder("Areas").setValue(this.plugin.settings.areasFolder).onChange(async (value) => {
      this.plugin.settings.areasFolder = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Sync Configuration" });
    new import_obsidian.Setting(containerEl).setName("Enable Auto Sync").setDesc("Automatically sync tasks at regular intervals").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableAutoSync).onChange(async (value) => {
      this.plugin.settings.enableAutoSync = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Sync Interval (minutes)").setDesc("How often to sync tasks (in minutes)").addText((text) => text.setPlaceholder("5").setValue(String(this.plugin.settings.syncInterval / 6e4)).onChange(async (value) => {
      const minutes = parseInt(value) || 5;
      this.plugin.settings.syncInterval = minutes * 6e4;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Template Configuration" });
    new import_obsidian.Setting(containerEl).setName("Template Folder").setDesc("Folder where templates are stored").addText((text) => text.setPlaceholder("Templates").setValue(this.plugin.settings.templateFolder).onChange(async (value) => {
      this.plugin.settings.templateFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Use Templater Plugin").setDesc("Enable integration with Templater plugin for advanced templates").addToggle((toggle) => toggle.setValue(this.plugin.settings.useTemplater).onChange(async (value) => {
      this.plugin.settings.useTemplater = value;
      await this.plugin.saveSettings();
    }));
  }
};
