/**
 * ObsidianTaskSource - Pure data source for Obsidian vault tasks
 *
 * Responsibilities:
 * - Scan vault for task files
 * - Parse task files into Task entities
 * - Watch for file changes and notify callbacks
 * - NO store manipulation - just pure data fetching
 *
 * This source provides tasks from the Obsidian vault by scanning the tasks folder
 * and parsing markdown files with task front-matter.
 */

import type { App } from "obsidian";
import type {
  DataSource,
  DataSourceWatchCallbacks,
} from "../../../sources/DataSource";
import type { Task } from "../../../core/entities";
import type { TaskSyncSettings } from "../../../types/settings";
import { ObsidianTaskOperations } from "../operations/TaskOperations";
import { ObsidianTaskReconciler } from "../../../core/TaskReconciler";
import { get } from "svelte/store";
import { taskStore } from "../../../stores/taskStore";

/**
 * ObsidianTaskSource class
 *
 * Implements DataSource<Task> for Obsidian vault tasks
 */
export class ObsidianTaskSource implements DataSource<Task> {
  readonly id = "obsidian";
  readonly name = "Obsidian Vault";
  readonly reconciler = new ObsidianTaskReconciler();

  private taskOperations: ObsidianTaskOperations;

  constructor(private app: App, private settings: TaskSyncSettings) {
    this.taskOperations = new ObsidianTaskOperations(app, settings);
  }

  /**
   * Load initial data by scanning the vault for task files
   *
   * @returns Promise resolving to array of tasks with IDs
   *
   * Note: Tasks are returned with IDs generated by buildEntity.
   * The store reducer will use the reconciler to match tasks by filePath
   * and preserve existing IDs when tasks are re-scanned.
   */
  async loadInitialData(): Promise<readonly Task[]> {
    console.log("[ObsidianTaskSource] Loading initial data...");

    // Scan existing task files in the vault
    // scanExistingTasks returns Task[] with IDs generated by buildEntity
    const tasks = await this.taskOperations.scanExistingTasks();

    console.log(`[ObsidianTaskSource] Loaded ${tasks.length} tasks from vault`);

    return tasks;
  }

  /**
   * Refresh data by re-scanning the vault
   *
   * @returns Promise resolving to array of tasks with IDs
   */
  async refresh(): Promise<readonly Task[]> {
    console.log("[ObsidianTaskSource] Refreshing data...");

    // Re-scan vault and return fresh data
    // This is the same as loadInitialData - we just re-scan everything
    return this.loadInitialData();
  }

  /**
   * Watch for file changes in the vault
   *
   * Uses incremental updates (onItemChanged, onItemDeleted) for efficiency.
   * Only parses the changed file using the cache parameter from metadataCache.on("changed").
   *
   * IMPORTANT: Does NOT listen to vault.on("create") because that fires when UI creates
   * tasks, causing duplicate processing. The metadataCache.on("changed") event fires for
   * both new files and modified files.
   *
   * @param callbacks - Callbacks for different types of changes
   * @returns Cleanup function to stop watching
   */
  watch(callbacks: DataSourceWatchCallbacks<Task>): () => void {
    console.log("[ObsidianTaskSource] Setting up file watchers...");

    const tasksFolder = this.settings.tasksFolder;

    // Helper to check if a file is in the tasks folder
    const isTaskFile = (file: any): boolean => {
      return file.path.startsWith(tasksFolder + "/");
    };

    // Listen for file modifications (front-matter changes)
    // Use metadataCache.on("changed") which provides cache parameter
    const onModify = this.app.metadataCache.on(
      "changed",
      async (file, _data, cache) => {
        if (isTaskFile(file)) {
          console.log(`[ObsidianTaskSource] Task file changed: ${file.path}`);

          try {
            // Parse only the changed file using the cache parameter
            const taskData = await this.taskOperations.parseFileToTaskData(
              file,
              cache
            );

            // Only notify if parsing succeeded (taskData is not null)
            if (taskData && callbacks.onItemChanged) {
              callbacks.onItemChanged(taskData);
            }
          } catch (error) {
            console.warn(
              `[ObsidianTaskSource] Skipping task file ${file.path}`,
              error
            );
          }
        }
      }
    );

    // Listen for file deletions
    const onDelete = this.app.vault.on("delete", async (file) => {
      if (isTaskFile(file)) {
        console.log(`[ObsidianTaskSource] Task file deleted: ${file.path}`);

        if (callbacks.onItemDeleted) {
          // Find the task by Obsidian key to get its ID
          const currentState = get(taskStore);
          const existingTask = currentState.tasks.find(
            (t) => t.source.keys.obsidian === file.path
          );

          if (existingTask) {
            // Notify about the deleted item
            callbacks.onItemDeleted(existingTask.id);
          }
        }
      }
    });

    // Return cleanup function
    return () => {
      console.log("[ObsidianTaskSource] Cleaning up file watchers...");
      this.app.metadataCache.offref(onModify);
      this.app.vault.offref(onDelete);
    };
  }
}
